#!/bin/bash

LOGBOOK_PATH="/home/touchte-codjo/.logbook"

if [ $# -lt 1 ]; then
	echo "Expect command : [add] or [serve]"
	echo "Usage :"
	echo "   1) logbook add \"title\" \"description\" \"image.png\" "
	echo "   2) logbook serve"
elif [ $# -ge 1 ]; then
	if [ "$1" = "add" ]; then
		# Minimum arguments requested : 3
		if [ $# -ge 3 ]; then 
			title=$2
			description=$3
			filename="" #for now
			today_date=$(date "+%y-%m-%d")
			instant=$(date "+%T")
			# We expect the 4-th arg to be the filename.	
			if [ $# -ge 4 ]; then	
				filename=$4
				if [ -f "$filename" ]; then
					# Check the existence of the repository of the day; if not create one
					if [ ! -d "$LOGBOOK_PATH/src/img/$today_date" ]; then
						mkdir -p "$LOGBOOK_PATH/src/img/$today_date"
					fi
					instant2=$(echo $instant | sed "s/:/-/g") # remplace ":" by "-" to better name a file
					cp $filename "$LOGBOOK_PATH/src/img/$today_date/$today_date-$instant2.png"
					# Above we still need to extract the real extension of the picture (.png, .jpg, etc...)
				else 
					echo "$filename is not a regular file (we also expect a *.png)"
					filename=""
					# This part really needs the comment above to be taken in consideration
				fi
			fi
			# Create or fill the note of the day at the current the time
			# If the journal of the day does not exit, create one !
			if [ ! -f "$LOGBOOK_PATH/src/$today_date.md" ]; then
				touch "$LOGBOOK_PATH/src/$today_date.md"
				echo "# DATE → $today_date" >> "$LOGBOOK_PATH/src/$today_date.md"
				echo "" >> "$LOGBOOK_PATH/src/$today_date.md"
				echo "" >> "$LOGBOOK_PATH/src/$today_date.md" # create the line 3
				#-- Update the SUMMARY.md file --
				sed "7i\\[$today_date](./$today_date.md)\n" "$LOGBOOK_PATH/src/SUMMARY.md" >> tmp_summary
				mv tmp_summary "$LOGBOOK_PATH/src/SUMMARY.md"
			fi
			#-- Fill the journal of the day --
			# If filename is not empty
			if [ ! -z "$filename" ]; then
				sed "3i\\### ($today_date $instant) $title \n$description \n![$today_date-$instant2.png](./img/$today_date/$today_date-$instant2.png) \n" "$LOGBOOK_PATH/src/$today_date.md" >> tmp_file
			else 
				sed "3i\\### ($today_date $instant) $title \n$description \n" "$LOGBOOK_PATH/src/$today_date.md" >> tmp_file
			fi
			mv tmp_file "$LOGBOOK_PATH/src/$today_date.md"
		else 
			echo "Expect at least 2 arguments."
			echo "Type lobbook help"
		fi
	elif [ "$1" = "serve" ]; then
		mdbook serve $LOGBOOK_PATH --open
	else
		echo "Expect command : [add] or [serve]"
		echo "Usage :"
		echo "   1) logbook add \"title\" \"description\" \"image.png\" "
		echo "   2) logbook serve"
	fi
fi
